[project]
name = "stocks-chatbot"
version = "0.1.0"
description = "Chatbot for stocks"
requires-python = ">=3.13"
dependencies = [
    "alpha-vantage>=3.0.0",
    "langchain[google-genai]>=0.3.25",
    "langgraph>=0.4.5",
]

[dependency-groups]
dev = [
    "ruff>=0.11.10",
]
