lint:
	uv run ruff format . && uv run ruff check . --fix

basics-chat:
	uv run python examples/basics/chat/main.py

basics-tools:
	uv run python examples/basics/tools/main.py

basics-memory:
	uv run python examples/basics/memory/main.py

basics-human:
	uv run python examples/basics/human/main.py

basics-state:
	uv run python examples/basics/state/main.py
