[project]
name = "langgraph-playground"
version = "0.1.0"
description = "Playground of LangGraph"
requires-python = ">=3.13"
dependencies = [
    "alpha-vantage>=3.0.0",
    "fredapi>=0.5.2",
    "langchain-community>=0.3.24",
    "langchain-tavily>=0.1.6",
    "langchain[anthropic,google-genai]>=0.3.25",
    "langgraph>=0.4.5",
    "langgraph-supervisor>=0.0.25",
    "langgraph-swarm>=0.0.11",
    "pandas>=2.2.3",
    "tiktoken>=0.9.0",
    "ta-lib>=0.6.3" # needs ta-lib C library installed on your system
]

[dependency-groups]
dev = [
    "ruff>=0.11.10",
]
